#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_base:
    path: /
    controller: App\Controller\DefaultController::index

app_login:
    path: /login/
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout/

app_admin:
    path: /admin/
    controller: App\Controller\DefaultController::admin

app_lucky_number:
    path: /lucky/number/
    controller: App\Controller\LuckyController::number

sms_base:
    path: /sms/
    controller: App\Controller\SMSController::account

sms_form:
    path: /sms/form/
    controller: App\Controller\SMSController::sms_form

sms_history:
    path: /sms/history/
    controller: App\Controller\SMSController::sms_history    

app_error_403:
    path: /access_denied/error403
    controller: App\Controller\ExceptionController::showException403